# Site wide configuration

title:            AIR project
locale:           en_US
# url:              http://localhost:4000

name: AIR project
description: Assessing the feasibility of exploring Venus' interior with balloons

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Quentin Brissaud
  avatar: quentin.jpg
  bio: "Geophysicist at NORSAR, Oslo."
  email: quentin@norsar.no
  disqus-shortname: quentinbrissaud
  twitter: QuentinBrissaud
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: QuentinBrissaud
  stackoverflow: 
  linkedin: 
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  workflowly: ydgBawDfMYKEb5cA

exclude: ["CNAME", ".htaccess", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
